repos:
  # Форматирование кода — black
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.14

  # Сортировка импортов — isort
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort

  # Проверка стиля кода — flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: .venv,venv,__pycache__,migrations,tests/settings.py
